cfunited.ui.Speakers = Ext.extend(Ext.Panel,{
	id:'speakers-card',
	fullscreen:true,
	title:'Orateurs',
	iconCls:'team',
	layout:'card',
	initComponent: function(){

		this.titlebar = new Ext.Toolbar({
			title:'Speakers',
			dock:'top'
		});		
	
		Ext.regModel("Speaker",{
			fields:['id','name','companyname','bio','topics']
		});
		
		var tpl = new Ext.XTemplate(
			'<tpl for=".">',
				'<div class="speaker">',
					'<strong>{name}</strong>',
				'</div>',
			'</tpl>'
		);
				
		this.speakers = new Ext.List({
			id:'speakerList',
			fullscreen:true,
			tpl:tpl,
			itemSelector: 'div.speaker',
			singleSelect:true,
			grouped:true,
			indexBar:true,
			dockedItems:[this.titlebar],
			store: new Ext.data.Store({
				model:'Speaker',
				sorters:'name',
				getGroupString : function(record){
					return record.get('name')[0];
				}
			})			
		});
		
		this.speakerDetails = new cfunited.ui.SpeakerDetails();
		
		this.items = [this.speakers,this.speakerDetails];
		
		cfunited.ui.Speakers.superclass.initComponent.apply(this, arguments);
		
		this.speakers.on('itemtap',this.onItemTap,this);
		
	},
	
	onBack: function(){
		//
	},
	
	onItemTap: function(view,index,item,e){
		var rec = view.store.getAt(index);		
		
		this.speakerDetails.loadSpeaker(rec.data);
		this.setCard(1);
	},

	onLoad: function(){
		Ext.getBody().mask(false, '<div class="loading">Loading&hellip;</div>');
		var speakers_data = new Object();
		
		speakers_data =	
		[
		{'id':50,'companyname':'Club Agile Rhône Alpes','bio':'Le Club Agile Rhône Alpes – CARA est une association loi 1901 qui se donne pour objectifs la promotion et la diffusion des méthodes agiles dans la région Rhône-Alpes par tous moyens de communication et d\'intervention: conférence, séminaire, rencontre, accompagnement, consulting, formation.','name':'CARA','topics':[{'id':10,'name':'Le mot des organisateurs'}]},
		{'id':54,'companyname':'','bio':'Karl Scotland Karl SCOTLAND est un praticien logiciel polyvalent de plus de 15 ans d’expérience dans les domaines du développement, de la gestion de projet, du leadership d’équipe, du coaching et de la formation.','name':'Scotland Karl','topics':[{'id':54,'name':'Karl Scotland“Starting An Agile Transition with Why”'}]},			
			{'id':55,'companyname':'','bio':'Jurgen APPELO est auteur, orateur, formateur, entrepreneur, illustrateur, développeur, manager, blogueur, lecteur, rêveur, leader et libre-penseur. Depuis 2008 Jurgen écrit un blogue populaire - www.noop.nl - qui traite de gestion de projet, de génie logiciel, de business, de développement personnel et de la théorie de complexité. Il est également l\'auteur de « Management 3.0 : Leading Agile Developers, Developing Agile Leaders» et orateur international','name':'Appelo Jurgen','topics':[{'id':55,'name':'How to Change the World'}]},
		{'id':1,'companyname':'Institut Agile','bio':'Laurent Bossavit est directeur de l\'Institut Agile, organisation indépendante qui a pour mission de promouvoir la recherche sur les pratiques agiles et de faciliter leur adoption dans les entreprises. Anciennement développeur avec plus de 20 ans d\'expérience pratique, il compte parmi les premiers découvreurs des pratiques agiles en France.','name':'Bossavit Laurent','topics':[{'id':1,'name':'Neuro-agilité: un nouveau regard sur la conception'},{'id':38,'name':'Atelier NeuroAgile'}]},		
		{'id':2,'companyname':'Jbrains','bio':'J. B. (Joe) Rainsberger helps software organizations better satisfy their customers and the businesses they support. Expert at delivering successful software, he writes, teaches and speaks about why delivering better software is important, but not enough. He helps clients improve their bottom line by coaching teams as well as leading change programs. He helps software organizations off the treadmill of over-commitment and under-delivery, addressing all aspects of software delivery including understanding the business, gelling the team and even writing great code. Learn more about how Joe will inspire your software organization at jbrains.ca, at conferences world-wide, or by writing him directly at me@jbrains.ca.','name':'Rainsberger J. B.','topics':[{'id':2,'name':'Les tests intégrés sont une arnaque!'}]},		
		{'id':3,'companyname':'Captive Studio','bio':'Programmeur extrême et responsable de production de jeu vidéo depuis 2006, Stéphane s\'est lancé en 2008 dans la création de la société Captive Studio pour produire des logiciels de divertissement. Stéphane est coordinateur du chapitre parisien de l\'IGDA et promeut l\'agilité dans l\'industrie française du jeu vidéo','name':'Hanser Stéphane','topics':[{'id':3,'name':'Alone in the dark'}]},
		{'id':4,'companyname':'','bio':'Chef de projet depuis 10 ans chez un éditeur de progiciels professionnels. Depuis plus de 6 ans nos projets intègrent une part de plus en plus importante de développements spécifiques. Avec 2 autres membres de l\'équipe projet, nous avons été moteur dans la mise en place de la méthode Scrum, où j\ai pris le rôle de Scrum Master.','name':'D\'Hennezel Nicolas','topics':[{'id':4,'name':'l\'Agilité ou comment doper l\'efficacité et la motivation des équipes'}]},		
		{'id':5,'companyname':'','bio':'','name':'Pattein Francis','topics':[{'id':4,'name':'l\'Agilité ou comment doper l\'efficacité et la motivation des équipes'}]},	
		{'id':6,'companyname':'','bio':'Consultant expérimenté et dans l\'entreprise depuis 5 ans, l\'un des moteurs de la mise en place de la méthode Scrum. Il a pris le rôle de Product Owner de part le fait qu\'il a réalisé toute la phase de définition de la solution avec le client avant la mise en place de l\'Agilité. Il a pris en main et maîtrisé très rapidement son rôle et les outils de la méthode qu\'il a fait évolué et adapté à notre contexte.','name':'Griffon Xavier','topics':[{'id':4,'name':'l\'Agilité ou comment doper l\'efficacité et la motivation des équipes'}]},		
		{'id':7,'companyname':'Effissens','bio':'DESS GRH DRH d\'ingénièrie Gérant d\'entreprise Enseignant consultant à GEM et l\'ecole nationale d\'architecture de grenoble','name':'Benameur Karim','topics':[{'id':7,'name':'Dépasser l\'efficacité pour être agile : la proposition de l\'effissens'}]},		
		{'id':8,'companyname':'Coupling Wave Solutions','bio':'Pierre est ingénieur de recherche et développement logiciel spécialisé dans la programmation orientée objet avec plus de 7 ans d\’expérience et a rejoint CWS en 2006. Il a été l’initiateur de l\’agilité au sein de l\’équipe et tient depuis le rôle de ScrumMaster (certifié Professional Scrum Master en Février 2011) et membre de l\’équipe SCRUM. ','name':'Taillard Pierre','topics':[{'id':8,'name':'Devenez le Product Owner de notre retour d’expérience'}]},		
		{'id':9,'companyname':'Coupling Wave Solutions','bio':'Sylvain est ingénieur de recherche et développement logiciel spécialisé dans la programmation orientée objet avec plus de 15 ans d\’expérience et a rejoint CWS en 2007. Il tient le rôle de membre de l\’équipe SCRUM.','name':'Pointeau-Carbanne Sylvain','topics':[{'id':8,'name':'Devenez le Product Owner de notre retour d’expérience'}]},		
		{'id':10,'companyname':'',bio:'Anne Laure aide les équipes de développement logiciel à construire de la valeur, en temps voulu, avec plaisir et en adoptant un rythme durable. Elle apporte cette aide en formant les équipes aux méthodes de gestion de projet et aux pratiques d\'ingenierie logicielle telles que Scrum et XP, en les coachant et en codant avec elles.','name':'Dalban Anne-Laure','topics':[{'id':8,'name':'Devenez le Product Owner de notre retour d’expérience'}]},				
		{'id':11,'companyname':'SAMSE','bio':'Arnaud Benistant est scrummaster au sein du groupe SAMSE. Présent dans la societé depuis presque 10 ans, il a participé à la construction du système d\'information du groupe en tant qu\'ingénieur puis en tant que scrummaster depuis 2 ans. Passionné par l\'agilité, il fait partager son experience sur le blog "Ca Scrum ! ".','name':'Benistant Arnaud','topics':[{'id':11,'name':'La session dont vous êtes le héros !'}]},		
		{'id':12,'companyname':'ut7','bio':'Emmanuel Etasse est coach, formateur  et associé de la société \/ut7. Il aide les organisations de développement logiciel à devenir des lieux où résultats, qualité de vie et plaisir, coexistent de façon durable.  Passionné de programmation, il a 14 ans d’expérience dans l\’industrie du logiciel, dont 6 ans dans la mise en œuvre et l’accompagnement des approches agiles (éditeurs logiciels, PME, DSI, grands comptes…).  Seul formateur scrum.org en France, Emmanuel enseigne Scrum à l’Ecole de Management des Système d\’Information à Grenoble. Emmanuel est aussi membre actif et cofondateur du Club Agile Rhône Alpes.','name':'Etasse Emmanuel','topics':[{'id':11,'name':'La session dont vous êtes le héros !'}]},			
		{'id':13,'companyname':'','bio':'Emmanuel agit en tant qu\’accompagnateur d’équipes, animateur de réunions, formateur, programmeur extrême, codexhibitionniste et agitateur public. Par le biais d\'armes non-conventionnelles, il aide les équipes produisant du logiciel à être plus efficaces dans leur travail, plus fières de leurs résultats et plus heureuses en général. Emmanuel est un spécialiste de la gestion de projet incrémentale, des structures émergeantes et des espaces de co-apprentissage. Il s\'intéresse aussi de manière déraisonnable à la programmation fonctionnelle en général et à Haskell en particulier. Un orateur régulier à de nombreuses conférences sur l\’Agilité, Emmanuel organise également la conférence annuelle Agile Open France. Il est l\’un des fondateurs du Dojo de développement de Paris, et un de ses membres assidus depuis sa création il y a six ans. Emmanuel est un des associés de la société \/ut7.','name':'Gaillot Emmanuel','topics':[{'id':13,'name':'Un Kata Marrant'}]},
		{'id':14,'companyname':'ut7','bio':'"Polyglote, accro au dernier degré des tests automatisés, célèbre pour ses sessions endiablées au Dojo Développement de Paris, Jonathan est un programmeur dans l\'âme. Il développe du logiciel depuis plus de dix ans, mais sa lecture du livre ""XP explained"" en 2004 a profondément changé sa manière d\'appréhender le métier de développeur - et ce n\'était que le début. Jonathan est à la recherche constante d\'occasions de montrer, partager et vivre pleinement la joie qu\'apporte l\'acte de programmation. Il est l\'un des associés de \/ut7.','name':'Perret Jonathan','topics':[{'id':13,'name':'Un Kata Marrant'}]},
		{'id':15,'companyname':'AgileToYou','bio':'Diplômé de l\’Ensimag en 1989, Alexandre découvre l\’Agilité en 2004 et prend en charge la promotion de l\’Agilité en Europe, Asie et Inde pour Yahoo International de 2005 à 2009. Début 2009, Alexandre décide de créer la société AGILETOYOU pour former et accompagner de nombreux clients désireux de devenir Agile (Orange, EDF, Total, Schneider, Thales, Samse, BBC …). Alexandre est de plus un orateur régulier des conférences nationales et préside le CARA (Club Agile Rhône Alpes) qui organise Agile Grenoble le 24 novembre 2011 ou plus de 500 personnes sont attendues.','name':'Boutin Alexandre','topics':[{'id':15,'name':'Des Jeux Agiles pour apprendre'}]},
		{'id':16,'companyname':'Persistent Systems','bio':'Chimiste de formation, Matthieu est Product Owner au sein de Persistent Systems depuis 2007 sur divers projets de logiciels scientifiques. Il travaille en méthode agile depuis 6 ans et a participé à leur mise en place comme client embarqué au sein de l\’équipe de développement puis comme Product Owner.','name':'Gironnet Matthieu','topics':[{'id':16,'name':'Démonstration \/ Kata BDD sur un logiciel pilotant un instrument'}]},
		{'id':17,'companyname':'Persistent Systems','bio':'Johanny  est développeur au sein de Persistent Systems depuis plusieurs années. Travaillant sur des logiciels scientifiques dans diverses équipes, il travaille en méthode agile depuis 5 ans. Il utilise quotidiennement le BDD depuis 1 an.','name':'Bergeron Johanny','topics':[{'id':16,'name':'Démonstration \/ Kata BDD sur un logiciel pilotant un instrument'}]},
		{'id':18,'companyname':'Axway','bio':'','name':'Mack Adams','topics':[{'id':18,'name':'Cartographie agile de la gestion des produits'}]},
		{'id':19,'companyname':'Morisseau Consulting','bio':'De formation Ingénieur ENSTA et architecte naval, Laurent MORISSEAU a travaillé plus de quinze ans dans l\'ingénierie logiciel. Actuellement gérant fondateur de la société Morisseau Consulting, il accompagne les entreprises et les équipes qui souhaitent évoluer vers l\'agilité (consulting, formation, coaching) et le Kanban. Il est l\'un des spécialistes en France de l\'Agilité, seul français certifié CSC (Certified Scrum Coach) avec plus de deux ans d’expérience en Kanban sur des projets significatifs. Il propose les premiers retours d’expérience sur le sujet à la conférence Agile 2010, formalise ses connaissances avec David Anderson, le père du Kanban. Depuis il anime des ateliers Kanban régulièrement et propose la seule formation en Français sur le sujet.','name':'Morisseau Laurent','topics':[{'id':19,'name':'Kanban, un tour d\'horizon'}]},
		{'id':20,'companyname':'','bio':'51 ans - Consultant et entrepreneur, j\'ai alterné la Direction opérationnelle de PMI indépendantes ou de filiales de groupes avec des interventions de conseil auprès de dirigeants d\'entreprises. Intervenant régulier à l\'Ecole Nationale des Ponts et Chaussées et à Grenoble Ecole de Management, j\'apprécie de partager mon expérience sur le thème de la performance globale des organisations, leur agilité étant ma principale préoccupation.','name':'Fleurat Jacques','topics':[{'id':20,'name':'Agilité et approche systémique du risque'}]},
		{'id':21,'companyname':'Google','bio':'','name':'Hunter Susan','topics':[{'id':21,'name':'"It\’s What You Don\’t Do That Counts'}]},
		{'id':22,'companyname':'Moodys Analytics','bio':'','name':'Megard Cyril','topics':[{'id':21,'name':'It\’s What You Don\’t Do That Counts'}]},
		{'id':23,'companyname':'','bio':'Claude a créé sa société de conseil en 1994. Depuis 2005, il se consacre à Scrum et aux méthodes agiles, en aidant les entreprises à les appliquer. Impliqué dans la communauté agile, il est Président de la SigmaT, membre du French SUG, membre fondateur de la Fédération Agile et Product Owner du logiciel Open Source iceScrum. Il est l\'auteur d’un blog de référence sur Scrum (Scrum, Agilité et rock\'n roll) et du premier livre sur Scrum en français (Scrum, le guide pratique de la méthode agile la plus populaire).','name':'Aubry Claude','topics':[{'id':23,'name':'"(ice)Scrum, agilité et rock\'n roll'}]},
		{'id':24,'companyname':'Kagilum','bio':'','name':'Barrier Vincent','topics':[{'id':24,'name':''},{'id':23,'name':'"(ice)Scrum, agilité et rock\'n roll'}]},
		{'id':25,'companyname':'','bio':'Jean-Philippe LECLERE et Josquin LOUVIER sont avocats spécialisés dans le droit des nouvelles technologies et notamment dans le conseil et le contentieux informatique. Ils interviennent régulièrement dans des dossiers impliquant l’utilisation des méthodes agiles.','name':'Leclere Jean-Philippe','topics':[{'id':25,'name':'La contractualisation d’un projet Agile : enjeux et pièges'}]},
		{'id':26,'companyname':'','bio':'Jean-Philippe LECLERE et Josquin LOUVIER sont avocats spécialisés dans le droit des nouvelles technologies et notamment dans le conseil et le contentieux informatique. Ils interviennent régulièrement dans des dossiers impliquant l’utilisation des méthodes agiles.','name':'Louvier Josquin','topics':[{'id':25,'name':'La contractualisation d’un projet Agile : enjeux et pièges'}]},
		{'id':27,'companyname':'Schneider Electric','bio':'Chef de projet logiciel (PC software) durant dix ans dans un département de recherche d’une société pétrolière puis au sein de la division Marketing de Schneider Electric Responsable méthodes et outils durant six ans au sein du service Customer Software & eBusiness de Schneider Electric. Actuellement expert processus de développement logiciel et qualimetire dans la division Stratégie et innovation de Schneider Electric. Compétences: •CMMI improvement leader (Our department reached CMMI level 3 in 2006) •ITIL (Certified itSMF in 2008) •Certified Scrum Master (2010)','name':'Dondey Hervé','topics':[{'id':27,'name':'Agile Offer Creation program in Schneider Electric'}]},
		{'id':28,'companyname':'Schneider Electric','bio':'','name':'Bergmann Erick','topics':[{'id':27,'name':'Agile Offer Creation program in Schneider Electric'}]},		
		{'id':29,'companyname':'ChangIT','bio':'','name':'Martinsson Johan','topics':[{'id':29,'name':'Maîtriser le legacy avec Mikado'}]},
		{'id':30,'companyname':'','bio':'','name':'Moquillon Miguel','topics':[{'id':29,'name':'Maîtriser le legacy avec Mikado'}]},
		{'id':31,'companyname':'Agilarium  ','bio':'Fabrice est passionné par l\'Agile : Scrum et Kanban en particulier. Il est impliqué dans des communautés telles que le Scrum User Group bordelais, le Club Lean Aquitaine et la SigmaT. Régulièrement, il publie un billet de rétrospective ou une traduction sur son blog Agilarium.fr. Il est consultant en Agilité chez Sopra Group.','name':'Aimetti Fabrice','topics':[{'id':31,'name':'Agile Portfolio'}]},
		{'id':32,'companyname':'AKQA','bio':'Sophie Freiermuth est Architecte Expérience Utilisateur dans l’une des plus prestigieuses agences créatives digitales, reconnue pour sa capacité technique autant que pour sa créativité. Sophie collabore au quotidien avec les équipes de développement sur des projets web, App et mobile pour des marques globales et une audience internationale. Passionnée par le challenge de créer une expérience positive pour des millions d\'utilisateurs ainsi que par les processus de développement et de travail, elle a travaillé en Agile au sein d\'Orange UK, Nokia et AKQA.','name':'Freiermuth Sophie','topics':[{'id':32,'name':'L\'architecte de l\’expérience utilisateur, un membre clé des projets front end Agile\/Lean: présentation du rôle, conseils de collaboration.'}]},
		{'id':33,'companyname':'','bio':'Pierre Vachon est un Coach agile et organisationnel ayant travaillé plusieurs années au Canada et aux États-Unis notamment en tant que Scrum Master et Scrum Coach. En france depuis quatre ans, il aide les grandes entreprises dans des projets de transformation et de transition vers les méthodes agiles. Il fait souvent de la formation Scrum, XP, Kanban, et Lean, et travaille également avec les managers en tant que consultant afin d\'optimiser et d\'améliorer la structure et l\'organisations des projets. Monsieur Vachon possède une formation en génie logiciel, en gestion de projets, et en administration des affaires. Il est certifié Scrum Master et Scrum Professional. Vous pouvez contacter monsieur Vachon directement à l\'adresse suivante : pierre.vachon@gmail.com','name':'Vachon Pierre','topics':[{'id':33,'name':'Une bonne histoire !'}]},
		{'id':34,'companyname':'','bio':'Développeur, chef de projet, directeur technique adjoint, operations manager : plus de 20 ans dans l\’édition logicielle. A vécu l\’agilité au quotidien - mise en place, coaching de scrum masters et product owners - pendant 4 ans, sur des projets industriels. Passionné par la créativité, le développement logiciel, le management et... la montagne.','name':'Vallée Thierry','topics':[{'id':34,'name':'Story Map : objectif feed-back !'}]},
		{'id':35,'companyname':'','bio':'Après quelques années en tant que développeur, Emilie Franchomme s\’est ensuite tournée vers la gestion de projets et l\’assistance à maîtrise d’ouvrage. Product Owner pendant 3 ans, elle est aujourd\'hui Scrum Master. Elle est passionnée par Scrum et les méthodologies Agiles, et s\’intéresse à tout ce qui peut permettre de délivrer du logiciel de qualité, satisfaisant les utilisateurs, tout en permettant aux équipes de s\’épanouir.','name':'Franchomme Emilie','topics':[{'id':35,'name':'Rétrospectives\’lab : décantation'}]},
		{'id':36,'companyname':'Sogeti','bio':'Leader sur les projets d\'innovation et acteur majeur sur l\'agilité et plus particulierement avec scrum, il est intervenu à la fois en tant que product owner et scrum master sur différents projets de developpement. ','name':'Bazzaro Fabrice','topics':[{'id':36,'name':'Scrum et innovation'}]},
		{'id':37,'companyname':'Sogeti','bio':'','name':'Barthe Elodie','topics':[{'id':36,'name':'Scrum et innovation'}]},
		{'id':38,'companyname':'AGILESSENCE','bio':'Je suis formateur, consultant et coach Agile. Dans l\’informatique depuis plus de vingt ans je suis intervenu dans de nombreux domaines du SI  en particulier  pendant 6 ans au service du e-commerce européen chez Hewlett Packard. Aujourd\'hui  j\'accompagne les organisation dans le XXIème siècle. Je porte l\'Agilité en tant que philosophie au service de l\'entreprise et mode d\'organisation des projets. ','name':'Jagodzinski Jean-François','topics':[{'id':38,'name':'Ce que vous devez savoir à propos de la contractualisation Agile'}]},
		{'id':39,'companyname':'Thales','bio':'Après une thèse dans le domaine des Documents Multimédia, Laurent a rejoint Kelkoo comme développeur java avancé. Passionné par l\'intégration continue et les outils d\'analyse de code, il a travaillé a mettre en place une plateforme d’intégration chez Kelkoo puis Yahoo. Depuis 2 ans il aide a la mise en place d\'une plateforme au service des équipes Agile d\'Agilent\/PersistentSAS.','name':'Gardais Guillaume','topics':[{'id':39,'name':'Git au quotidien'}]},
		{'id':40,'companyname':'Persistent SAS','bio':'','name':'Tardif Laurent','topics':[{'id':39,'name':'Git au quotidien'}]},
		{'id':41,'companyname':'La boite à Outils','bio':'Grenoblois, montagnard citadin, Directeur informatique et membre de la DG de « La boite à Outils », groupe SAMSE. Inspiré par les pratiques AGILE (XP, SCRUM, Lean) depuis 2005. Je suis aussi passionné par le management et président du groupe GERME* « DOJO » de Grenoble. * Groupes d\’entrainement et de réflexion au Management des Entreprises. Les courants de pensés suivants m’influence aussi fortement : « L\’élément humain» de Will Schutz , « La spirale dynamique » de Clare W Graves, « La vision Intégrale » de Ken Wilber','name':'Dufau-Joël Frédéric','topics':[{'id':41,'name':'Comment rendre nos entreprises Agile ?'}]},
		{'id':42,'companyname':'Groupe Open','bio':'Directeur de projets informatiques chez OPEN (TEAMLOG) à Grenoble, Jean dirige des projets et des TMA en mode agile et enseigne en tant que Professeur Affilié à Grenoble Ecole de Management. Jean est également référent agile régional et coach agile au sein d’OPEN, en charge de la diffusion de l’agilité et du partage des pratique. Plus sur mon parcours sur viadeo et linkedin.','name':'Dupuis Jean','topics':[{'id':42,'name':'REX Bascule en agile d\'un portefeuille de projets et TMA'}]},
		{'id':43,'companyname':'SNCF  ','bio':'Christophe DUPLAIX est PO SNCF sur le périmètre des trains communicants et de la plateforme PSCS sol-bord de communication entre trains et applications métiers','name':'Duplaix Christophe','topics':[{'id':42,'name':'REX Bascule en agile d\'un portefeuille de projets et TMA'}]},
		{'id':44,'companyname':'Maison de l\'Initiative  ','bio':'* Formation et rencontre avec les concepteurs de l\'XP début 2000  * Fondateur de l\'association Extreme Programming France, 2000 * Les premiers articles (article dans Langages et Systèmes, 01 Informatique...) en français sur ce phénomène,2000 * Auteur de « Maîtriser les projets avec l\'Extreme Programming », 2004* Conférences et séminaires ""agiles"" (2000 à aujourd\'hui)* Membre du Conseil de l\'asso SigmaT. Cette association basée à Toulouse a pour but de promouvoir l\'agilité dans le Sud-Ouest * Membre de la Fédération agile. voir aussi http://etreagile.thierrycros.net/home/?category/Qui-est-Etre-Agile"','name':'Cros Thierry','topics':[{'id':44,'name':'Manager agile : concrètement'}]},
		{'id':45,'companyname':'La boîte à Outils','bio':'"Responsable équipe de chefs de projet fonctionnel (Product Owner) avec un état d\'esprit Agile. Pratique de l\'agilité depuis 2005 (XP, SCRUM, LEAN/KANBAN)"','name':'Cuttaz Jérôme','topics':[{'id':45,'name':'Jouer pour être plus Agile'}]},
		{'id':46,'companyname':'La boîte à Outils','bio':'','name':'Joseph Cédric','topics':[{'id':45,'name':'Jouer pour être plus Agile'}]},
		{'id':47,'companyname':'La boîte à Outils','bio':'Chef de projet et Scrumaster. Pratique l\'agilité depuis 2005 (XP, SCRUM, LEAN/KANBAN)','name':'Lesne Vincent','topics':[{'id':45,'name':'Jouer pour être plus Agile'}]},
		{'id':48,'companyname':'Orange','bio':'Je suis responsable depuis 4 ans de promouvoir l\’agilité, la « définir » pour Orange, l\’industrialiser et accompagner opérationnellement les projets volontaires, j’ai pu expérimenter à peu près tous les pièges liés à l\’introduction de l’agilité dans une entreprise de grande taille.','name':'Genin Rémy','topics':[{'id':48,'name':'Retour sur 4 ans d\’industrialisation de l\’agilité chez Orange'}]},
		{'id':49,'companyname':'Thales Services','bio':'Coach et formatrice agile depuis plus d\'un an, je tiens également à garder un pied dans des projets et équipes agiles via un rôle de Scrum Master. J\'ai coaché et formé différents projets, dans différents contextes et avec des personnes très différentes. Je contribue également au CARA et à Agile Grenoble depuis leurs créations et me lance depuis l\'année dernière dans des conférences agiles. Ces différentes expériences apportent toujours plus d\'eau à mon moulin et me permettent d\'apprendre en permanence. L\'agilité est pour moi une véritable façon d\'être et de travailler, plus humaine, plus logique et plus efficace, et qui me correspond totalement.','name':'Hanot Laurence','topics':[{'id':49,'name':'Y a t-il un pilote dans le projet ?'}]},
		{'id':50,'companyname':'SOGILIS','bio':'','name':'Zwiebel Etienne','topics':[{'id':50,'name':'Externalisation agile d\'un projet avionique : les ingrédients d\'un succès'}]},
		{'id':51,'companyname':'Thales','bio':'','name':'Bonzy Jonathan','topics':[{'id':51,'name':'Symphonie pour PHP industrialisé en agilité majeure'}]},
		{'id':52,'companyname':'Best Of Media','bio':'','name':'Nazarian Marc','topics':[{'id':51,'name':'Symphonie pour PHP industrialisé en agilité majeure'}]},
		{'id':53,'companyname':'Best Of Media','bio':'','name':'Huguet Bernard','topics':[{'id':51,'name':'Symphonie pour PHP industrialisé en agilité majeure'}]},
		{'id':54,'companyname':'Agence Interactive','bio':'Spécialiste en architecture de systèmes Web et fort de plus de 20 ans d\'expérience en ingénierie logicielle et management d\'équipes et de projets, j’ai acquis plusieurs expériences sur des projets open-source d\'envergure dont des serveurs d\'application et applications B2C/B2B dans les secteurs du tourisme, de l\'événementiel, du management et de l\'enseignement. J’anime régulièrement des conférences ainsi que des formations dans les domaines de l\'Agilité et de l\'Open-source. Impliqué depuis plusieurs années dans le développement de startups du Web2.0 en France et en Californie, j’ai rejoint en 2009 Agence Interactive, en tant que Directeur Technique Associé, pour les accompagner dans la conduite du changement vers l\’Agilité. ','name':'Ney Christophe','topics':[{'id':54,'name':'KANBAN et SCRUM au sein d\'une agence digitale'}]},
		{'id':55,'companyname':'Persistent SAS','bio':'Product owner at Persistent Systems - 2011 Product OwnerAgilent Technologies -2010 Junior project manager Varian 2002 – November 2010 (8 years)','name':'Coelho Isabelle','topics':[{'id':55,'name':'Nos Product Owner (Pos), ils ressemblent à quoi aujourd\’hui ?'}]},
		{'id':57,'companyname':'Persistent SAS','bio':'Product Owner (Business Analyst) at Persistent Systems 2011 Product owner (Business Analyst) at Agilent Technologies 2010 Product owner (Business Analyst) at Varian, Inc. October 2007 – May 2010 (2 years 8 months) Grenoble Area, France','name':'Remont Solange','topics':[{'id':55,'name':'Nos Product Owner (Pos), ils ressemblent à quoi aujourd\’hui ?'}]},
		{'id':59,'companyname':'Optimhommes','bio':'-Titulaire d\'un DESS en stratégie RH, DU de sociologie des organisations en mutation, -13 ans expérience en GRH. ex DRH et membre du Comité de direction société RTSS France (105p - 2 établissements) -Coach professionnel depuis 2010 -Enseignant Grenoble Ecole de Management (GEM) en Stratégie et en Agilité -Fondateur et Co-dirigeant de la société OptimHommes ','name':'Tarradas Thomas','topics':[{'id':59,'name':'Agilité et GRH'}]},
		{'id':61,'companyname':'Enalean','bio':'Manuel est un le directeur technique et co-fondateur de la société Enalean. Il pratique l\'Agilité (Scrum & Kanban) depuis 4 ans et baigne dans la communauté Libre (Open Source) depuis 10 ans.','name':'Vacelet Manuel','topics':[{'id':61,'name':'L\'agilité support au co-développement'}]},
		{'id':62,'companyname':'Itecor','bio':'','name':'Wasitova Silvana','topics':[{'id':62,'name':'Overcoming Distances: Scrum with Distributed Teams'}]}	
		];					
				Ext.getCmp('speakerList').getStore().loadData(speakers_data);
				Ext.getBody().unmask();	
        
	}
	
});
